# Experiment Configuration for Step 12: Model Refinement
[sampling]
# Total images to use in the experiment
sample_sizes = [1000]
random_state = 230420
test_size = 0.15
val_size = 0.15

[modes]
    [modes.standard]
    inaturalist = 0.3
    local_ccmt_ghana = 0.3
    yolo_mcdd_india = 0.3
    meta_plantseg = 0.1

    [modes.balanced]
    inaturalist = 0.4
    local_ccmt_ghana = 0.2
    yolo_mcdd_india = 0.2
    meta_plantseg = 0.2

    [modes.cross_source]
    local_ccmt_ghana = 0.3
    yolo_mcdd_india = 0.3
    meta_plantseg = 0.3
    inaturalist_leak = 0.1

# Define specific experimental runs to execute
[experiments]
    run_standard = true
    run_balanced = true
    run_cross_source = true

[models]
# Including Dummy for baseline comparison
list = ["Dummy", "MobileNetV2", "XGBoost"]
# Deep Learning specific
epochs = 7
batch_size = 32
fine_tune_last_blocks = 8

[visualization]
save_grad_cam = true
save_roc_curve = true
output_dir = "observability/grad-cam"
num_samples = 5
