# Experiment Configuration for Step 12: Model Refinement

[sampling]
# Total images to use in the experiment
sample_sizes = [500]
random_state = 230420
test_size = 0.15
val_size = 0.15

# Define the composition of the training/test pool. 
[composition]
    [composition.inaturalist]
    dataset_weight = 0.2
    healthy_pct = 50
    diseased_pct = 50

    [composition.local_ccmt_ghana]
    dataset_weight = 0.4
    healthy_pct = 50
    diseased_pct = 50

    [composition.yolo_mcdd_india]
    dataset_weight = 0.4
    healthy_pct = 50
    diseased_pct = 50

# Define specific experimental runs to execute
[experiments]
    run_standard = true
    run_balanced = true
    run_cross_source = true

[models]
# Including Dummy for baseline comparison
list = ["Dummy", "MobileNetV2", "XGBoost", "RandomForest"]
# Deep Learning specific
epochs = 7
batch_size = 32
fine_tune_last_blocks = 8

[visualization]
save_grad_cam = true
save_roc_curve = true
output_dir = "observability/grad-cam"
num_samples = 5
