[general]
download_images = false
log_level = "INFO"
raw_data_path = "data/raw"
processed_data_path = "data/processed"

[sources.inaturalist]
enabled = true
refetch = false

base_url = "https://api.inaturalist.org/v1"
taxon_id = 47126        # Plantae
project_ids = [49595, 124267, 227684, 47428, 255039]
per_page = 200          # максимум дозволений API
max_pages = 5
rate_limit_seconds = 5.0

[sources.kaggle]
enabled = false
dataset = "plantvillage/plantvillage-dataset"

[load]
format = "sqlite"
target_path = "data/processed/observations.db"
table_name = "observations"
